name: Build DSi IA

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: DSi-IA
          path: "*.nds"
